### ISSUE TITLE
What's the return type for Google_Service_Drive_Resource_Files::export() ?

### ISSUE THREAD

**Issue by chris-fa** [google/google-api-php-client-services#49] opened 2017-02-13 13:59 UTC
I'm trying to download a PDF using the [basic example](https://developers.google.com/drive/v3/web/manage-downloads) but I haven't been able to make PHP return's it as a `Content-Type: application/pdf` response. 

So far the only lead I have is that I'm running `strlen($content)` on the returned type by `Google_Service_Drive_Resource_Files::export()` but it says it's an object not a string. What type is returned?

**Comment by mattwhisenhunt** [comment] 2018-03-19 18:38
Duplicate of https://github.com/google/google-api-php-client/issues/1280

**Closed by mattwhisenhunt** 2018-03-19 18:38 UTC
Labels: type: question
