### ISSUE TITLE
Google_Service not found

### ISSUE THREAD

**Issue by Abdillah** [google/google-api-php-client-services#118] opened 2018-06-29 06:59 UTC
This library not work out of the box, because it missing `Google_Service` class. Maybe, add `https://github.com/google/google-api-php-client` into `composer.json`?

# Reproduce
1. Init composer project
2. Install this library `composer require google/apiclient-services:dev-master`.
3. Create simple file that load the library.

```
<?php
require_once __DIR__."/vendor/autoload.php";

$service = new Google_Service_Sheets("TOKEN");
$spreadsheetId = 'SHEET_ID';

// TODO: Assign values to desired properties of `requestBody`:
$requestBody = new Google_Service_Sheets_BatchUpdateValuesRequest();
$requestBody->setValueInputOption("RAW");

$response = $service->spreadsheets_values->batchUpdate($spreadsheetId, $requestBody);
$requestBody->setData([
    "range" => "Sheet!A5",
    "majorDimension" => "ROW",
    "values" => [[ 'TRYING' ]],
]);
```

# Expected
Not err. Work out of the box.

# Unexpected
Get runtime fatal error.
```
Fatal error: Class 'Google_Service' not found in /projectfolder/vendor/google/apiclient-services/src/Google/Service/Sheets.php on line 31
```

**Comment by mattwhisenhunt** [comment] 2018-06-29 15:36
Duplicate of google/google-api-php-client#1218

**Closed by mattwhisenhunt** 2018-06-29 15:36 UTC

**Comment by mattwhisenhunt** [comment] 2018-06-29 15:38
@Abdillah google-api-php-client-services is not meant as a stand-alone library. It will be installed when you [install apiclient](https://github.com/google/google-api-php-client#installation). Thanks for creating this issue. Please let us know if you have anymore questions.

**Comment by acmwallace** [comment] 2022-03-28 21:42
This still seems to be a problem in 2022. The problem for us is that these warning messages show up in web pages running with the Google apiclient-services in our composer.json. Someone suggested editing the autoloader to not try and alias these, but that seems like a terrible idea. Any other suggestions?
