### ISSUE TITLE
CalendarList getItems() function should return an array instead CalendarListEntry

### ISSUE THREAD

**Issue by elenitaex5** [google/google-api-php-client-services#110] opened 2018-03-22 08:07 UTC
Hi all,
I'm using Google Calendar Service and extracting all my calendars with getItems() function. 
from apiclient-services/src/Google/Service/Calendar/CalendarList.php

```
 /**
   * @return Google_Service_Calendar_CalendarListEntry
   */
  public function getItems()
  {
    return $this->items;
  }

```
This function in fact returns an array of CalendarListEntry not a single CalendarListEntry, so it should be

```
 /**
   * @return Google_Service_Calendar_CalendarListEntry[]
   */

```
Result of getItems :  
```
array (size=5)
  0 => 
    object(Google_Service_Calendar_CalendarListEntry)[2364]
      protected 'collection_key' => string 'defaultReminders' (length=16)
      public 'accessRole' => string 'reader' (length=6)
      public 'backgroundColor' => string '#b3dc6c' (length=7)
      public 'colorId' => string '10' (length=2)
      .....
  1 => 
    object(Google_Service_Calendar_CalendarListEntry)[2365]
      protected 'collection_key' => string 'defaultReminders' (length=16)
      public 'accessRole' => string 'owner' (length=5)
      public 'backgroundColor' => string '#a47ae2' (length=7)
      public 'colorId' => string '24' (length=2)
    ....
  2 => 
    object(Google_Service_Calendar_CalendarListEntry)[2366]
      protected 'collection_key' => string 'defaultReminders' (length=16)
      public 'accessRole' => string 'owner' (length=5)
      public 'backgroundColor' => string '#fad165' (length=7)
      public 'colorId' => string '12' (length=2)
     ....
```

Thanks

**Comment by mattwhisenhunt** [comment] 2018-03-22 16:59
Duplicate of https://github.com/google/google-api-php-client/issues/443

**Comment by mattwhisenhunt** [comment] 2018-03-22 17:00
Thanks for the heads up! This library is autogenerated so we can't make the fix right there in the services code.

**Closed by mattwhisenhunt** 2018-03-22 17:00 UTC

**Comment by elenitaex5** [comment] 2018-03-23 10:29
ok, so a little question. How people is solving this problem? because i'm fixing vendor classes in my own project but if someone clone it and make a vendor install, there gonna be a lot of errors using that Classes

**Comment by mattwhisenhunt** [comment] 2018-03-26 19:07
@elenitaex5, are you just fixing it to get type hinting working in your IDE/editor?
