### ISSUE TITLE
Incorrect/missing Type hinting for Drive API

### ISSUE THREAD

**Issue by karensg** [google/google-api-php-client-services#96] opened 2017-12-07 13:41 UTC
I experience some issues for type hinting in Drive API service.
For example:

- PermissionList.php, methods `setPermissions` and `getPermissions` should have `Google_Service_Drive_Permission[]` as type.
- The same is the case for `FileList` and `setFiles`, `getFiles` methods

Also lots of public methods in `Files.php` do not have a `@return` statement which makes it unconvenient to use with linting tools.

I see that the sdk is autogenerated. Is there a way how we could fix this problem?

**Comment by mattwhisenhunt** [comment] 2017-12-09 00:49
Unfortunately, no. The generator package is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. 
Two possible workarounds are: 
- Manually fix the type hinting comments and monitor updates to affected files and port autogenerated changes over manually.
- Use the last release of the [generator](https://pypi.python.org/pypi/google-apis-client-generator/1.4.2) as a starting point and make the changes you desire. The second workaround requires some Python experience.

**Comment by karensg** [comment] 2017-12-11 09:25
Hi Matt,

Thanks for your answer. I will ignore the warnings in my IDE for now and will keep an eye on the updates :)

**Comment by mattwhisenhunt** [comment] 2018-03-19 18:58
Duplicate of google/google-api-php-client#443

**Closed by mattwhisenhunt** 2018-03-19 18:58 UTC
Labels: priority: p2, status: will not fix, type: type hinting

**Comment by karensg** [comment] 2020-02-19 14:31
Not really a duplicate as the phpdoc comments are present but just wrong. Would be still great to fix this.
