### ISSUE TITLE
Google Custom Search: Google_Service_Customsearch_Context->getFacets() returns Null

### ISSUE THREAD

**Issue by MarkusGehrig** [google/google-api-php-client-services#80] opened 2017-08-16 06:56 UTC
We are implementing the "Google Customsearch API" in TYPO3 at the moment and had some problems with the getFacets methode of the Google_Service_Customsearch_Context Class. 

We get back a Object, but all Fields have the Value Null. With a print_r of the Object I can see the correct values, but they are stored in modelData. (See print_r and code below).

We have the same problem with:
getQueries and
getPromotions and
getSearchInformation

Print_R:
```
Array
(
    [0] => Google_Service_Customsearch_ContextFacets Object
        (
            [internal_gapi_mappings:protected] => Array
                (
                    [labelWithOp] => label_with_op
                )

            [anchor] => 
            [label] => 
            [labelWithOp] => 
            [modelData:protected] => Array
                (
                    [0] => Array
                        (
                            [label] => kompetenzen
                            [anchor] => Kompetenzen
                            [label_with_op] => more:kompetenzen
                        )

                )

            [processed:protected] => Array
                (
                )

        )

    [1] => Google_Service_Customsearch_ContextFacets Object
        (
            [internal_gapi_mappings:protected] => Array
                (
                    [labelWithOp] => label_with_op
                )

            [anchor] => 
            [label] => 
            [labelWithOp] => 
            [modelData:protected] => Array
                (
                    [0] => Array
                        (
                            [label] => projekte
                            [anchor] => Projekte
                            [label_with_op] => more:projekte
                        )

                )

            [processed:protected] => Array
                (
                )

        )

    [2] => Google_Service_Customsearch_ContextFacets Object
        (
            [internal_gapi_mappings:protected] => Array
                (
                    [labelWithOp] => label_with_op
                )

            [anchor] => 
            [label] => 
            [labelWithOp] => 
            [modelData:protected] => Array
                (
                    [0] => Array
                        (
                            [label] => arbeiten_bei_uns
                            [anchor] => Arbeiten bei uns
                            [label_with_op] => more:arbeiten_bei_uns
                        )

                )

            [processed:protected] => Array
                (
                )

        )

    [3] => Google_Service_Customsearch_ContextFacets Object
        (
            [internal_gapi_mappings:protected] => Array
                (
                    [labelWithOp] => label_with_op
                )

            [anchor] => 
            [label] => 
            [labelWithOp] => 
            [modelData:protected] => Array
                (
                    [0] => Array
                        (
                            [label] => über_uns
                            [anchor] => Über uns
                            [label_with_op] => more:über_uns
                        )

                )

            [processed:protected] => Array
                (
                )

        )

    [4] => Google_Service_Customsearch_ContextFacets Object
        (
            [internal_gapi_mappings:protected] => Array
                (
                    [labelWithOp] => label_with_op
                )

            [anchor] => 
            [label] => 
            [labelWithOp] => 
            [modelData:protected] => Array
                (
                    [0] => Array
                        (
                            [label] => aktuelles
                            [anchor] => Aktuelles
                            [label_with_op] => more:aktuelles
                        )

                )

            [processed:protected] => Array
                (
                )

        )

    [5] => Google_Service_Customsearch_ContextFacets Object
        (
            [internal_gapi_mappings:protected] => Array
                (
                    [labelWithOp] => label_with_op
                )

            [anchor] => 
            [label] => 
            [labelWithOp] => 
            [modelData:protected] => Array
                (
                    [0] => Array
                        (
                            [label] => offene_stellen
                            [anchor] => Offene Stellen
                            [label_with_op] => more:offene_stellen
                        )

                )

            [processed:protected] => Array
                (
                )

        )

    [6] => Google_Service_Customsearch_ContextFacets Object
        (
            [internal_gapi_mappings:protected] => Array
                (
                    [labelWithOp] => label_with_op
                )

            [anchor] => 
            [label] => 
            [labelWithOp] => 
            [modelData:protected] => Array
                (
                    [0] => Array
                        (
                            [label] => ansprechpartner
                            [anchor] => Ansprechpartner
                            [label_with_op] => more:ansprechpartner
                        )

                )

            [processed:protected] => Array
                (
                )

        )

)
```

Code:

```
$client = new \Google_Client;

// set the application name
$client->setApplicationName('cabag_googlesearch');

// get developer key
$apiKey = $this->apiKeyRepository->findBestMatchingApiKey();
    
$client->setDeveloperKey($apiKey['googleapikey']);

$this->service = new \Google_Service_Customsearch($client);

optParams = array_merge(['cx' => $apiKey['googlesearchengineid']], $optParams);
optParams = array_merge(['lr' => 'de'], $optParams);
optParams = array_merge(['hl' => 'de'], $optParams);

$resultRequest = $this->service->cse->listCse($searchTerm, optParams);

$result = $resultRequest->getItems();
$context = $resultRequest->getContext();
$facets = $context->getFacets();

print_r($facets);
```

**Comment by MarkusGehrig** [comment] 2017-08-16 08:00
We have now made a Workaround with the Methode toSimpleObject(). Works for us but Problem still isn't fixed now. 

```
$client = new \Google_Client;

// set the application name
$client->setApplicationName('cabag_googlesearch');

// get developer key
$apiKey = $this->apiKeyRepository->findBestMatchingApiKey();
    
$client->setDeveloperKey($apiKey['googleapikey']);

$this->service = new \Google_Service_Customsearch($client);

optParams = array_merge(['cx' => $apiKey['googlesearchengineid']], $optParams);

$resultRequest = $this->service->cse->listCse($searchTerm, optParams);

$result = $resultRequest-> toSimpleObject();

print_r($result);
```

**Comment by mattwhisenhunt** [comment] 2018-06-19 18:20
Duplicate of google/google-api-php-client#932

**Closed by mattwhisenhunt** 2018-06-19 18:20 UTC
Labels: :rotating_light:, status: investigating, triage me
