### ISSUE TITLE
new firebasedynamiclinks-ipv6 endpoint causing `cURL error 7` from official php Docker 

### ISSUE THREAD

**Issue by arubacao** [google/google-api-php-client-services#86] opened 2017-09-14 09:49 UTC
After an upgrade from `v0.18`  to `>=v0.19` I'm unable to make API calls.
The underlying cURL obvs. doesn't like something.

```
[2017-09-14 09:12:46] local.ERROR: GuzzleHttp\Exception\ConnectException: cURL error 7:  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
Stack trace:
#0 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 ...
```
Curl Error 7 means `Failed to connect() to host or proxy.`
I figured that the cause of the problem is the new endpoint: `'url' => 'https://firebasedynamiclinks-ipv6.googleapis.com/v1/shortLinks?key=xxx`

The endpoints have been updated [here](https://github.com/google/google-api-php-client-services/commit/be9eb25296f5797b00bbdac09a7fabef58eaa3dd#diff-6449adecf59e61020579b27d448679aeL48) from `https://firebasedynamiclinks.googleapis.com/` => `https://firebasedynamiclinks-ipv6.googleapis.com/`

I'm using the official php docker image `7.1.9-fpm` without any modifications to curl or curl libs

I know this is not an actual issue of `google-api-php-client-services`, but maybe we can find a solution here.

Cheers

**Comment by mattwhisenhunt** [comment] 2017-12-12 00:08
Duplicate of #97

**Closed by mattwhisenhunt** 2017-12-12 00:08 UTC
