### ISSUE TITLE
PHP Notice iterating over Google_Service_Webmasters_SitesListResponse::$siteEntry

### ISSUE THREAD

**Issue by DerManoMann** [google/google-api-php-client-services#75] opened 2017-07-24 03:47 UTC
Since the last vendor update I now see this error/notice running some of my tests:
````
Symfony\Component\Debug\Exception\ContextErrorException: Notice: Indirect modification of overloaded property Google_Service_Webmasters_SitesListResponse::$siteEntry has no effect
.../vendor/google/apiclient/src/Google/Collection.php:20
````
The code looks something like this (notice thrown on the foreach):
````
        $siteListResponse = $googleWebmasterService->sites->listSites();

        $count = 0;
        foreach ($siteListResponse as $item) {
            ++$count;
        }
````

Environment:
````
$ php -v
PHP 7.1.7 (cli) (built: Jul  6 2017 13:31:15) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.7, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
````
````
$ composer show |grep google
google/apiclient                         v2.2.0             Client library for Google APIs
google/apiclient-services                v0.15              Client library for Google APIs
google/auth                              v1.0               Google Auth Library for PHP
````

**Comment by bshaffer** [comment] 2017-07-24 19:41
Hmm, I am unable to reproduce this. I [wrote a test case](https://github.com/google/google-api-php-client/compare/master...bshaffer:test-for-issue-75?expand=1) and it ran just fine

My PHP version:

```bash
php -v
PHP 7.1.3 (cli) (built: Mar 28 2017 21:57:28) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

**Comment by mattwhisenhunt** [comment] 2017-12-12 01:27
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.

**Closed by mattwhisenhunt** 2017-12-12 01:27 UTC
